experiment:
    project: "one_d_piece_l256"
    name: "one_d_piece_l256_eval"
    output_dir: "checkpoints/one_d_piece_l256_stage2_run1"
    max_train_examples: 1_281_167
    save_every: 10_000
    eval_every: 10_000
    generate_every: 500
    log_every: 50
    log_grad_norm_every: 1_000
    resume: True
    explanation: "L-256 size One-D-Piece model"
    length: 256

model:
    type: "one_d_piece"
    vq_model:
        codebook_size: 4096
        token_size: 12
        use_l2_norm: True
        commitment_cost: 0.25
        # vit arch
        vit_enc_model_size: "large"
        vit_dec_model_size: "large"
        vit_enc_patch_size: 16
        vit_dec_patch_size: 16
        num_latent_tokens: 256
        finetune_decoder: True
        # relax assertion
        strict_length_assertion: False
    
losses:
    discriminator_start: 20_000
    quantizer_weight: 0.0
    discriminator_factor: 1.0
    discriminator_weight: 0.01
    perceptual_loss: "convnext_s"
    perceptual_weight: 0.1
    reconstruction_loss: "l2"
    reconstruction_weight: 1.0
    lecam_regularization_weight: 0.001

dataset:
    params:
        train_shards_path_or_url: "/data/dataset/imagenet/imagenet-train-{000000..000320}.tar"
        eval_shards_path_or_url: "/data/dataset/imagenet/imagenet-val-{000000..000049}.tar"
        num_workers_per_gpu: 12
    preprocessing:
        resize_shorter_edge: 256
        crop_size: 256
        random_crop: False
        random_flip: False

training:
    gradient_accumulation_steps: 1
    per_gpu_batch_size: 256
    mixed_precision: "bf16"
    enable_tf32: True
    enable_wandb: True
    use_ema: True
    seed: 42
    max_train_steps: 500_000
    num_generated_images: 2
    max_grad_norm: 1.0
